#!/bin/sh

if [ "${SCRIPT_DEBUG}" = "true" ] ; then
    set -x
    echo "Script debugging is enabled, allowing bash commands and their arguments to be printed as they are executed"
fi

SRCCONF=/tmp/src/configuration
echo "HERE HERE HERE HERE"
if [ -d ${SRCCONF} ]; then
  echo "Copying config files from project..."
  echo "1----created the dir"
  mkdir -p $AMQ_HOME/conf
echo "i----created the dir"
ls -l $AMQ_HOME/conf 
  cp -v ${SRCCONF}/* $AMQ_HOME/conf/
fi

# Remove java tmp perf data dir owned by 185
rm -rf /tmp/hsperfdata_jboss

exit 0
